AMREX_HOME ?= ../../../../..

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM        = 2
#DIM       = 3

USE_CUDA   = TRUE
COMP 	   = cuda
# COMP	   = gnu

USE_MPI    = FALSE
USE_OMP    = TRUE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv
